//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDePharmacie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionDePharmacie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_icon_icons_com_52393 {
            get {
                object obj = ResourceManager.GetObject("add_icon-icons.com_52393", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap big_pill_hand_doctor_169241_1924 {
            get {
                object obj = ResourceManager.GetObject("big-pill-hand-doctor_169241-1924", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Caucasian_female_head_woman_person_2855 {
            get {
                object obj = ResourceManager.GetObject("Caucasian_female_head_woman_person_2855", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caucasian_head_man_person_people_avatar_2859 {
            get {
                object obj = ResourceManager.GetObject("caucasian_head_man_person_people_avatar_2859", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeup_doctor_hold_clipboard_making_notes_write_diagnosis_48369_18603 {
            get {
                object obj = ResourceManager.GetObject("closeup-doctor-hold-clipboard-making-notes-write-diagnosis_48369-18603", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collection_pharmacist_illustrations_23_2148521829 {
            get {
                object obj = ResourceManager.GetObject("collection-pharmacist-illustrations_23-2148521829", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_delete_exit_1577 {
            get {
                object obj = ResourceManager.GetObject("delete_delete_exit_1577", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doctor_character_background_1270_84 {
            get {
                object obj = ResourceManager.GetObject("doctor-character-background_1270-84", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doctors_concept_illustration_114360_1515 {
            get {
                object obj = ResourceManager.GetObject("doctors-concept-illustration_114360-1515", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doctors_concept_illustration_114360_1525 {
            get {
                object obj = ResourceManager.GetObject("doctors-concept-illustration_114360-1525", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doctors_nurses_team_23_2148497394 {
            get {
                object obj = ResourceManager.GetObject("doctors-nurses-team_23-2148497394", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap drugs_bottle_medical_icon_24877_51505 {
            get {
                object obj = ResourceManager.GetObject("drugs-bottle-medical-icon_24877-51505", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap drugs_bottle_medical_icon_24877_515051 {
            get {
                object obj = ResourceManager.GetObject("drugs-bottle-medical-icon_24877-515051", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_icon_icons_com_52382 {
            get {
                object obj = ResourceManager.GetObject("edit_icon-icons.com_52382", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flat_salesman_character_holding_contract_document_23_2147885529 {
            get {
                object obj = ResourceManager.GetObject("flat-salesman-character-holding-contract-document_23-2147885529", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flat_salesman_character_holding_contract_document_23_21478855291 {
            get {
                object obj = ResourceManager.GetObject("flat-salesman-character-holding-contract-document_23-21478855291", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap head_medical_man_avatar_person_2837 {
            get {
                object obj = ResourceManager.GetObject("head_medical_man_avatar_person_2837", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medical_care_design_24877_49709 {
            get {
                object obj = ResourceManager.GetObject("medical-care-design_24877-49709", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medical_word_tiny_cartoon_doctors_flat_banner_81522_4192 {
            get {
                object obj = ResourceManager.GetObject("medical-word-tiny-cartoon-doctors-flat-banner_81522-4192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medicine_drugs_white_25030_44583 {
            get {
                object obj = ResourceManager.GetObject("medicine-drugs-white_25030-44583", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medicine_flat_design_1212_670 {
            get {
                object obj = ResourceManager.GetObject("medicine-flat-design_1212-670", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medicine_flat_design_1212_6701 {
            get {
                object obj = ResourceManager.GetObject("medicine-flat-design_1212-6701", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medicine_pills_capsules_healthcare_devices_169241_532 {
            get {
                object obj = ResourceManager.GetObject("medicine-pills-capsules-healthcare-devices_169241-532", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mix_race_doctors_pharmacists_team_standing_pharmacy_counter_modern_drugstore_interior_medicine_healthcare_concept_horizontal_portrait_48369_24458 {
            get {
                object obj = ResourceManager.GetObject("mix-race-doctors-pharmacists-team-standing-pharmacy-counter-modern-drugstore-inte" +
                        "rior-medicine-healthcare-concept-horizontal-portrait_48369-24458", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online_doctor_with_computer_23_2148525681 {
            get {
                object obj = ResourceManager.GetObject("online-doctor-with-computer_23-2148525681", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap people_buying_medical_products_modern_drugstore_front_view_pharmacy_store_building_exterior_medicine_healthcare_concept_horizontal_full_length_48369_24825 {
            get {
                object obj = ResourceManager.GetObject("people-buying-medical-products-modern-drugstore-front-view-pharmacy-store-buildin" +
                        "g-exterior-medicine-healthcare-concept-horizontal-full-length_48369-24825", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap people_working_science_lab_23_2148479660 {
            get {
                object obj = ResourceManager.GetObject("people-working-science-lab_23-2148479660", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pharmacist_23_2148174589 {
            get {
                object obj = ResourceManager.GetObject("pharmacist_23-2148174589", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pharmacist_counter_pharmacy_6280_722 {
            get {
                object obj = ResourceManager.GetObject("pharmacist-counter-pharmacy_6280-722", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pharmacist_counter_pharmacy_6280_7221 {
            get {
                object obj = ResourceManager.GetObject("pharmacist-counter-pharmacy_6280-7221", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pharmacy_illustration_with_doctor_holding_tablet_buy_medicine_36082_597 {
            get {
                object obj = ResourceManager.GetObject("pharmacy-illustration-with-doctor-holding-tablet-buy-medicine_36082-597", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pharmacy_with_doctor_nurse_counter_36082_543 {
            get {
                object obj = ResourceManager.GetObject("pharmacy-with-doctor-nurse-counter_36082-543", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pharmacy_with_pharmacist_client_counter_36082_469 {
            get {
                object obj = ResourceManager.GetObject("pharmacy-with-pharmacist-client-counter_36082-469", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pharmacy_with_pharmacist_client_counter_36082_496 {
            get {
                object obj = ResourceManager.GetObject("pharmacy-with-pharmacist-client-counter_36082-496", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pharmacy_with_pharmacist_client_counter_36082_529 {
            get {
                object obj = ResourceManager.GetObject("pharmacy-with-pharmacist-client-counter_36082-529", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pharmacy_with_pharmacist_client_counter_36082_556 {
            get {
                object obj = ResourceManager.GetObject("pharmacy-with-pharmacist-client-counter_36082-556", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pharmacy_with_pharmacist_client_counter_36082_604 {
            get {
                object obj = ResourceManager.GetObject("pharmacy-with-pharmacist-client-counter_36082-604", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pills_medical_10732 {
            get {
                object obj = ResourceManager.GetObject("pills_medical_10732", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pills_pot_icon_icons_com_76239 {
            get {
                object obj = ResourceManager.GetObject("pills_pot_icon-icons.com_76239", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap prescription_icon_icons_com_58843 {
            get {
                object obj = ResourceManager.GetObject("prescription_icon-icons.com_58843", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap receipt_shopping_icon_icons_com_49849 {
            get {
                object obj = ResourceManager.GetObject("receipt_shopping_icon-icons.com_49849", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap science_laboratory_illustration_1284_19152 {
            get {
                object obj = ResourceManager.GetObject("science-laboratory-illustration_1284-19152", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap set_doctors_characters_48866_327 {
            get {
                object obj = ResourceManager.GetObject("set-doctors-characters_48866-327", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap set_pills_suspensions_bottles_74855_225 {
            get {
                object obj = ResourceManager.GetObject("set-pills-suspensions-bottles_74855-225", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sign_emergency_code_sos_23_icon_icons_com_57202 {
            get {
                object obj = ResourceManager.GetObject("sign-emergency-code-sos_23_icon-icons.com_57202", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap young_doctors_health_professional_team_23_2148485703 {
            get {
                object obj = ResourceManager.GetObject("young-doctors-health-professional-team_23-2148485703", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
